build test:
  stage: test
  image: golang
  script:
    - go version
    - go build .
    - go test -v ./...

go lint:
  stage: test
  image: golang
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.32.0
    - golangci-lint run

version check:
  stage: test
  image: golang
  script:
    - diff -u VERSION <(grep "var version = " trezord.go | cut -f 2 -d '"')

#Gitlab does not support xgo building without hacking the base xgo image, for now builds are done manually until we find a better solution.
